---
- name: Get Architecture3 jar file # This needs to be updated to the latest release of consonance dependencies!
  raw: sudo wget https://www.dropbox.com/s/p254pqswn3o53xg/consonance-arch-2.0.0-alpha.16-SNAPSHOT.jar -O /home/ubuntu/consonance-arch-{{ consonance_arch_version }}.jar
  #https://www.dropbox.com/s/giy9ayxlvpoohiz/consonance-arch-2.0-alpha.11-SNAPSHOT.jar?dl=1 dest=/home/ubuntu/consonance-arch-{{ consonance_arch_version }}.jar
  #get_url: url=https://seqwaremaven.oicr.on.ca/artifactory/simple/seqware-release/io/consonance/consonance-arch/{{ consonance_arch_version }}/consonance-arch-{{ consonance_arch_version }}.jar dest=/home/ubuntu/consonance-arch-{{ consonance_arch_version }}.jar

# The "endless" flag for the worker is not a true/false, it's "--endless" or "".
- name: Conditionally turn endless_worker_flag on
  set_fact: endless_worker_flag=" --endless "
  when: endless_worker is defined and endless_worker

- name: Conditionally turn endless_worker_flag off
  set_fact: endless_worker_flag=""
  when: endless_worker is not defined or not endless_worker

- name: Get kill-worker scriptls
  template: src=kill_worker_daemon.j2 dest=/home/ubuntu/kill_worker_daemon.sh

- name: Get run-worker script
  template: src=run_worker_daemon.j2 dest=/home/ubuntu/run_worker_daemon.sh

- name: queueHost is
  debug: var={{ queueHost }}

- name: Template workerConfig
  template: src=workerConfig.j2 dest=/home/ubuntu/workerConfig.ini owner=ubuntu

- name: Create .seqware directory
  file: path=/home/ubuntu/.seqware state=directory owner=ubuntu
  when: seqware_use_custom_settings is defined and seqware_use_custom_settings

- name: Copy base custom seqware settings
  copy: src=../files/seqware_settings.ini dest=/home/ubuntu/.seqware/settings owner=ubuntu
  when: seqware_use_custom_settings is defined and seqware_use_custom_settings

- name: Uncomment the custom seqware settings, IF you've requested that.
  replace: dest=/home/ubuntu/workerConfig.ini regexp='^(\#seqware-)(.*)$' replace='seqware-\2' backup=yes owner=ubuntu
  when: seqware_use_custom_settings is defined and seqware_use_custom_settings

- name: Copy over keys/credentials for workers.
  copy: src={{ item }} dest=/root/.aws owner=root
  with_fileglob:
    - /root/.aws/*

- name: Copy over dockstore credentials
  copy: src={{ item }} dest=/root/.dockstore/ owner=root
  with_fileglob:
    - /root/.dockstore/*

- name: Install setuptools
  raw: sudo pip install setuptools==36.5.0

- name: Install avro
  raw: sudo pip install avro==1.8.1

- name: Install schema-salad
  raw: sudo pip install schema-salad==2.6.20170806163416

- name: Install cwltool
  raw: sudo pip install cwltool==1.0.20170217172322

# end dcc-storage
- name: Run worker as daemon
  become_user: root
  shell: chdir=/home/ubuntu nohup bash /home/ubuntu/run_worker_daemon.sh &
